# Generated by Django 4.0.2 on 2022-04-07 22:13

import BookCreator.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCreator',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('teacherId', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('contents', djongo.models.fields.ArrayField(model_container=BookCreator.models.Page)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subtitle', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
